language: node_js
sudo: false
node_js:
  - "stable"
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: build & test
      script: 
        - npm install
        - npm run build
        - npm run test
    - stage: bump version
      script: 
        - git config user.email "infinite.harbor@gmail.com"
        - git config user.name "Deployment Bot"
        - git remote rm origin
        - git remote add origin https://infiniteharbor:${GITHUBOAUTH}@github.com/infiniteharbor/infinity-utilities.git
        - git push --set-upstream origin master
        - git checkout master
        - git status
        - npm run gen-docs
        - npm run release
    - stage: deploy npm
      script: 
        - npm install
        - npm run build
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - npm publish        
stages:
  - build & test
  - name: bump version
    if: branch = master
  - name: deploy npm
    if: branch = master