language: node_js
sudo: false
node_js:
  - "stable"
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: test
      script: 
        - npm install
        - npm run build
        - npm run test
    - stage: compile
      script:
        - npm install
        - npm run build
        - npm run gen-docs
        - git config user.email "infinite.harbor@gmail.com"
        - git config user.name "Compiler Bot"
        - git remote rm origin
        - git remote add origin https://infiniteharbor:${GITHUBOAUTH}@github.com/infiniteharbor/everfinity-utilities.git
        - git push --set-upstream origin master
        - git checkout master
        - git add .
        - git commit -m "Automated Build [skip ci]"
        - git push
    - stage: release
      script: 
        - git config user.email "infinite.harbor@gmail.com"
        - git config user.name "Deployment Bot"
        - git remote rm origin
        - git remote add origin https://infiniteharbor:${GITHUBOAUTH}@github.com/infiniteharbor/everfinity-utilities.git
        - git push --set-upstream origin master
        - git checkout master
        - npm run release
    - stage: publish
      script: 
        - npm install
        - npm run build
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - npm publish ./lib --access public   
stages:
  - test
  - name: compile
    if: branch = master AND \
        env(GITHUBOAUTH) IS present AND \
        type IN (push)
  - name: release
    if: branch = master AND \
        env(GITHUBOAUTH) IS present AND \
        type IN (push)
  - name: publish
    if: branch = master AND \
        env(NPM_TOKEN) IS present AND \
        type IN (push)