language: node_js
sudo: false
node_js:
  - "stable"
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: build & test
      script: 
        - npm install
        - npm run build
        - npm run test
    - stage: bump version
      script: 
        - git config user.email "infinite.harbor@gmail.com"
        - git config user.name "Deployment Bot"
        - git remote add origin-deploy https://infiniteharbor:${GITHUBOAUTH}@github.com/infiniteharbor/infinity-utilities.git
        - npm run release
        #- git push --quiet --set-upstream origin-deploy master
    - stage: deploy npm
      script: 
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        

stages:
  - build & test
  - name: bump version
    if: branch = master
  - name: deploy npm
    if: branch = master