version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1

jobs:
  build-test:
    <<: *defaults  
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - run: npm build
      - run:
          name: Run Tests
          command: npm test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
          
      - add_ssh_keys:
          fingerprints:
          - "83:e0:2c:fe:b2:50:3f:91:cc:ef:25:01:ec:74:0f:25" 
      - run: git config user.email "infinite.harbor@gmail.com"
      - run: git config user.name "Deployment Bot"
      - run: 
          name: Create New Release Version
          command: npm run release
      - run:
          name: Authenticate with Registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish Package
          command: npm publish
            
workflows:
  version: 2
  master-deploy:
    jobs:
      - build-test
      #     filters:
      #       tags:
      #         only: /^v.*/
      - deploy:
          requires:
            - build-test
          filters:
            branches:
              only: master